<h2>Procedure verzoek Wet openbaarheid van bestuur</h2>
<h3>Fase 1: Verzoek</h3>
<p>Het proces wordt gestart met een schriftelijk verzoek aan een bestuursorgaan. Het verzoek betreft het openbaar maken van documenten over beleid. Je hoeft niet aan te geven waarom je de documenten openbaar wilt (<a href="http://wetten.overheid.nl/BWBR0005252/geldigheidsdatum_15-02-2013#HoofdstukIII_Artikel3" class="urlextern" title="http://wetten.overheid.nl/BWBR0005252/geldigheidsdatum_15-02-2013#HoofdstukIII_Artikel3"  rel="nofollow">artikel 3, lid 3 Wob</a>). Sommige bestuursorganen bevestigen de ontvangst van het verzoek, anderen niet.</p>
<p>Als het verzoek niet voldoende specifiek geformuleerd is, dan kan het bestuurs­orgaan de verzoeker om een toelichting vragen (<a href="http://wetten.overheid.nl/BWBR0005252/geldigheidsdatum_15-02-2013#HoofdstukIII_Artikel3" class="urlextern" title="http://wetten.overheid.nl/BWBR0005252/geldigheidsdatum_15-02-2013#HoofdstukIII_Artikel3"  rel="nofollow">artikel 3, lid 4 Wob</a>). De termijn voor het nemen van een beslissing wordt dan opgerekt met het aantal dagen tussen het verzoek om een aanvulling en dagtekening van de aanvulling.</p>
<p>Het bestuursorgaan is verplicht om “zo spoedig mogelijk”, maar niet later dan vier weken, op het verzoek te beslissen (<a href="http://wetten.overheid.nl/BWBR0005252/geldigheidsdatum_15-02-2013#HoofdstukIII_Artikel6" class="urlextern" title="http://wetten.overheid.nl/BWBR0005252/geldigheidsdatum_15-02-2013#HoofdstukIII_Artikel6"  rel="nofollow">artikel 6, lid 1 Wob</a>).</p>
<p>Als de termijn voor het nemen van een beslissing niet kan worden gehaald mag het bestuursorgaan de beslissing met vier weken verdagen. De verdaging moet gemotiveerd worden en voor het aflopen van de initiële termijn aan de verzoeker bekend zijn gemaakt (<a href="http://wetten.overheid.nl/BWBR0005252/geldigheidsdatum_15-02-2013#HoofdstukIII_Artikel6" class="urlextern" title="http://wetten.overheid.nl/BWBR0005252/geldigheidsdatum_15-02-2013#HoofdstukIII_Artikel6"  rel="nofollow">artikel 6, lid 2 Wob</a>).</p>
<p>Soms heeft het verzoek betrekking op documenten waar anderen ook belang bij hebben, zoals een rapport opgesteld door een externe bedrijf. Het bestuurs­orgaan is verplicht om deze belanghebbenden om hun zienswijze ten aanzien van het openbaar maken van de documenten te vragen. Het bestuurs­orgaan stuurt daartoe de belanghebbenden een schriftelijk verzoek en stelt een termijn, van bijvoorbeeld vier weken, voor een reactie. De termijn voor het nemen van een beslissing op het eigenlijke verzoek wordt opgeschort met het aantal dagen tussen het verzoek om een zienswijze en de ontvangst van die zienswijze of de gestelde termijn voor de ontvangst van een zienswijze als de belanghebbende niet reageert.  (<a href="http://wetten.overheid.nl/BWBR0005252/geldigheidsdatum_15-02-2013#HoofdstukIII_Artikel6" class="urlextern" title="http://wetten.overheid.nl/BWBR0005252/geldigheidsdatum_15-02-2013#HoofdstukIII_Artikel6"  rel="nofollow">artikel 6, lid 3 en 4 Wob</a>,  <a href="http://wetten.overheid.nl/BWBR0005537/Hoofdstuk4/Titel41/Afdeling412/Artikel48/geldigheidsdatum_15-02-2013" class="urlextern" title="http://wetten.overheid.nl/BWBR0005537/Hoofdstuk4/Titel41/Afdeling412/Artikel48/geldigheidsdatum_15-02-2013"  rel="nofollow"> artikel 4:8 Awb</a>)</p>
<p>Als een bestuursorgaan om andere redenen de termijn niet kan halen, kan het bestuursorgaan, in overleg met de verzoeker een extra uitstel voor het nemen van een beslissing afspreken.</p>
<p>Maar op een gegeven moment is de termijn voor het nemen van een beslissing echt verlopen. Omdat de beslissing, genomen op de laatste dag, ook verzonden moet worden, kan pas enkele dagen na het verlopen van de termijn bepaald worden of het bestuursorgaan zich aan de termijn heeft gehouden.</p>
<h3>Fase 2: Bezwaar</h3>
<p>Als de verzoeker van mening is dat de beslissing van het bestuursorgaan onjuist is, kan de verzoeker bezwaar aantekenen. Aantekenen van bezwaar kan door een brief te sturen aan het bestuursorgaan, onder vermelding van de gronden van bezwaar. De termijn voor het nemen van een beslissing op een bezwaar wordt gerekend vanaf de dag nadat de primaire beslissing is genomen: alle  belanghebbenden krijgen zes weken de tijd om bezwaar aan te tekenen en het bestuursorgaan krijgt daarna zes weken de tijd om een beslissing op het bezwaar te nemen.</p>
<p>Aan zo&#039;n bezwaarschrift zijn voorwaarden verbonden, zoals dat het bezwaar tijdig aangetekend moet zijn en dat het bezwaar gemotiveerd moet worden. Als een van de vereisten ontbreekt zal het bestuursorgaan de verzoeker in de gelegenheid stellen de beslissing aan te vullen. De termijn voor het nemen van een beslissing wordt opgeschort met het aantal dagen tussen het verzoek om de aanvulling en de dagtekening van de aanvulling.</p>
<p>Als de termijn voor het nemen van een beslissing niet kan worden gehaald mag het bestuursorgaan de beslissing met zes weken verdagen. De verdaging moet gemotiveerd worden en voor het aflopen van de initiële termijn aan de verzoeker bekend zijn gemaakt.</p>
<p>En ook hier geldt dat het bestuurs­orgaan verplicht is om belanghebbenden hun zienswijze ten aanzien van het openbaar maken van de documenten te vragen. Het bestuurs­orgaan stuurt daartoe de belanghebbenden een schriftelijk verzoek en stelt een termijn, van bijvoorbeeld vier weken, voor een reactie. De termijn voor het nemen van een beslissing op het eigenlijke verzoek wordt opgeschort met het aantal dagen tussen het verzoek om een zienswijze en de ontvangst van die zienswijze of de gestelde termijn voor de ontvangst van een zienswijze als de belanghebbende niet reageert.  In deze fase kan het bestuursorgaan een adviescommissie instellen. Dat is een semi-onafhankelijke commissie die beide partijen hoort en vervolgens aan het bestuursorgaan een advies uitbrengt. Het instellen van zo&#039;n commissie betekent ook een extra opschorting van het nemen van het besluit met zes weken.</p>
<p>Als een bestuursorgaan om andere redenen de termijn niet kan halen, kan het bestuursorgaan, in overleg met de verzoeker een extra uitstel voor het nemen van een beslissing afspreken.</p>
<p>Maar op een gegeven moment is de termijn voor het nemen van een beslissing echt verlopen. Omdat de beslissing, genomen op de laatste dag, ook verzonden moet worden, kan pas enkele dagen na het verlopen van de termijn bepaald worden of het bestuursorgaan zich aan de termijn heeft gehouden.</p>
<h3>Fase 3: Beroep</h3>
<p>Het kan natuurlijk zijn dat de verzoeker het ook niet eens is met de beslissing op bezwaar. In dat geval staat het de verzoeker vrij om de zaak ook inhoudelijk aan de rechter voor te leggen. Dat gebeurt door het aantekenen van beroep of te wel het opsturen van een beroepsschrift aan de rechtbank.</p>
<p>Als er al een beroepsprocedure voor het niet tijdig nemen van een beslissing op een bezwaar liep en het bestuursorgaan neemt alsnog een beslissing, dan kan het reeds lopende beroep worden omgezet in een inhoudelijk beroep.</p>
<h3>Afdwingen van een beslissing</h3>
<p>Als blijkt dat het bestuursorgaan, ondanks het verlopen van de termijn, geen beslissing heeft genomen, kan het bestuursorgaan in gebreke worden gesteld. De verzoeker moet dat schriftelijk doen. Na ontvangst van de ingebrekestelling heeft het bestuursorgaan twee weken de tijd om een beslissing te nemen. Na die twee weken begint, maximaal vier weken, een dwangsom te lopen. Voor elke dag dat het bestuursorgaan dan nog geen beslissing heeft genomen, is een dwangsom verschuldigd.</p>
<p>Als het bestuursorgaan geen beslissing neemt kan de verzoeker ook een rechtszaak beginnen en de rechter vragen het bestuursorgaan op te leggen alsnog snel een beslissing te nemen. Dat kan overigens ook al vroeg in het proces, het is niet noodzakelijk om het bestuursorgaan eerst in gebreke te stellen. Om deze procedure te beginnen moet beroep worden aangetekend bij de rechtbank.</p>
<p>Het is goed om te realiseren dat een ingebrekestelling of het aantekenen van beroep meerdere keren kan voorkomen in het hele proces. Het kan zijn dat een bestuursorgaan in zowel de eerste fase (initiële verzoek) als in de tweede fase (bezwaar) niet tijdig een beslissing neemt.</p>

<h2>Automatisch berekende velden</h2>
<h3>Actie in</h3>
<p>Het &quot;actie in&quot; veld geeft aan over hoeveel dagen weer iets moet of staat te gebeuren. Het kan bijvoorbeeld zijn dat de termijn voor het nemen van een beslissing door het bestuursorgaan afloopt, of dat bezwaar moet zijn aangetekend.</p>
<p>Als er nog geen beslissing op het verzoek- of bezwaarschrift is genomen, geldt de datum waarop de termijn voor het nemen van een beslissing verloopt als datum waarop actie ondernomen moet worden. Als er wel een beslissing is genomen, geldt de deadline voor het aantekenen van respectievelijk het bezwaar of beroep als datum waarop actie ondernomen (had) moeten worden.</p>
<p>Als het bestuursorgaan in gebreke is gesteld voor het niet nemen van een beslissing, dan wordt de berekening daarop gebaseerd. Gemakshalve wordt er vanuit gegaan dat de gebruiker niet eerder beroep voor het niet nemen van een beslissing aantekent, dan na het verstrijken van de maximale termijn waarover het bestuursorgaan een dwangsom is verschuldigd naar aanleiding van de ingebrekestelling. Volgens de wet gaat die dwangsom pas lopen op &quot;de dag waarop twee weken zijn verstreken na de dag waarop [...] het bestuursorgaan van de aanvrager een schriftelijke ingebrekestelling heeft ontvangen&quot; en is het aantal dwangsomdagen niet meer dan 42 dagen. De &quot;actie in&quot; wordt berekend op basis van de ontvangstdatum van de ingebrekestelling, vermeerderd met 1 dag (&quot;de dag na de dag waarop&quot;) + 14 dagen (&quot;twee weken&quot;) + 42 dagen (&quot;ten hoogste 42 dagen&quot;). Als de ontvangstdatum niet bekend is, wordt de verzenddatum gebruikt, vermeerderd met nog een extra dag.</p>
<p>Als bij de rechtbank beroep is aangetekend, dan is er geen &quot;actie in&quot; datum. De afhandeling, en dus ook het moment van de volgende stap, is dan volledig afhankelijk van de rechtbank en slecht te voorspellen.</p>
<h3>Aantal dagen herstel verzuim (bij verzoek en bezwaar)</h3>
<p>Het veld &quot;aantal dagen herstel verzuim&quot; geeft aan met hoeveel dagen de beslissing op het verzoek of bezwaar is opgeschort, nadat het bestuursorgaan om een aanvulling gevraagd heeft.</p>
<p>Het veld wordt berekend op basis van een tweetal data. De eerste datum waarmee gerekend wordt is de datum van de dagtekening van het verzoek om de aanvulling. Voor de tweede datum wordt gekeken naar de datum waarop de aanvulling verzonden is.  Als wel een aanvulling is verzonden wordt de datum van ontvangst van de aanvulling door het bestuursorgaan gebruikt. Als die datum niet bekend is, omdat het bestuursorgaan de ontvangst nog niet bevestigd heeft, wordt gerekend met de datum van verzending van de aanvulling, vermeerderd met 1 dag. Als de aanvulling na de gestelde datum is verzonden, wordt gerekend met de gestelde deadline. Is geen aanvulling verzonden wordt ook de datum van de deadline voor aanvulling gebruikt. Het aantal dagen opschorting van de beslissing is het verschil tussen de datum van dagtekening van verzoek van de aanvulling en de tweede datum.</p>
<h3>Aantal dwangsom dagen (bij verzoek en bezwaar)</h3>
<p>Het &quot;aantal dagen dwangsom&quot; veld geeft aan over hoeveel dagen het bestuursorgaan, nadat het in gebreke is gesteld voor het niet nemen van een beslissing, al een dwangsom is verschuldigd.</p>
<p>De wet stelt een paar voorwaarden: er zijn 14 dagen verstreken na het verlopen van de termijn voor het nemen van de beslissing &eacute;n er zijn 14 dagen verstreken na de ontvangstdatum van de ingebrekestelling.<p>
<p>Bijvoorbeeld, stel dat de dag van ontvangst van de ingebrekestelling 19 juni 2012 is. Dan is de dag na de ontvangst dus de 20 juni 2012. De dag waarop daarna twee weken zijn verstreken is 4 juli 2012. Dat is de dag waarop het bestuursorgaan voor het eerst een dwangsom is verschuldigd. Op 2 augustus heeft het bestuursorgaan dan eindelijk een beslissing genomen. Dan is de laatste dag waarop het bestuursorgaan in gebreke was dus 1 augustus. Het totaal aantal dwangsom dagen is daarmee dus 29.</p>
<p>Voor het berekenen van het veld wordt in de eerste plaats gekeken naar de datum van de dag waarop het bestuursorgaan de ingebrekestelling heeft ontvangen. Als er al een beslissing op het verzoek is genomen, wordt de datum van de dagtekening van die beslissing als einddatum gebruikt. Als er nog geen beslissing is genomen, dan wordt daarvoor de huidige datum gebruikt. Het verschil tussen die twee data, verminderd met 15 dagen en met een maximum van 42 dagen is het &quot;aantal dagen dwangsom&quot;.</p>
<h3>Aantal resterende dagen in termijn voor nemen beslissing</h3>
<p>Dit veld geeft aan hoeveel dagen nog over zijn binnen de termijn voor het nemen van een beslissing. Verloopt de termijn voor het nemen van een beslissing op 13 mei en is het vandaag 7 mei, dan resterende 6 dagen. In het geval dat de termijn overschreden is, is de termijnsoverschreiding weergegeven.</p>
<p>Het veld wordt berekend uit het verschil tussen de dag waarop een beslissing is genomen en de dag waarop de beslissing uiterlijk genomen had moeten worden. Is er nog geen beslissing genomen, dan wordt gerekend met de dag van vandaag.</p>
<h3>Berekende dwangsom (bij verzoek en bezwaar)</h3>
<p>De dwangsom bedraagt op basis van de berekende dagen: de eerste veertien dagen &euro; 20 per dag, de daaropvolgende veertien dagen &euro; 30 per dag en de overige dagen &euro; 40 per dag. Het totaal aantal dagen is maximaal 42 dagen. Het totaal bedrag kan dus maximaal 1.260 euro zijn.</p>
<h3>Deadline voor nemen beslissing op verzoek</h3>
<p>Dit veld toont de datum waarop het bestuursorgaan een beslissing op het verzoek moet hebben genomen.</p>
<p>Als uitgangsdatum wordt gerekend met de datum waarop het verzoek is ontvangen. Is geen ontvangstdatum bekend, dan wordt gerekend met de dag van verzending, vermeerderd met 1 dag. Deze datum wordt vervolgens vermeerderd met 28 dagen als beslissingstermijn en met, voor zover van toepassing, het aantal dagen waarmee de beslissing door het bestuursorgaan is verdaagd, het aantal dagen dat het bestuursorgaan extra uitstel is verleend, het aantal dagen waarmee de behandeling is uitgesteld na een verzoek om een aanvulling en het aantal dagen waarmee het verzoek opgeschort omdat het bestuursorgaan derden om hun zienswijze heeft gevraagd.</p>
<h3>Deadline voor nemen beslissing op bezwaar</h3>
<p>Dit veld toont de datum waarop het bestuursorgaan een beslissing op het bezwaar moet hebben genomen.</p>
<p>Als uitgangsdatum wordt gerekend met de datum waarop het verzoek is ontvangen. Is geen ontvangstdatum bekend, dan wordt gerekend met de dag van verzending, vermeerderd met 1 dag. Deze datum wordt vervolgens vermeerderd met 42 dagen als beslissingstermijn en met, voor zover van toepassing, het aantal dagen waarmee de beslissing door het bestuursorgaan is verdaagd, het aantal dagen dat het bestuursorgaan extra uitstel is verleend, het aantal dagen waarmee de behandeling is uitgesteld na een verzoek om een aanvulling, het aantal dagen waarmee het verzoek opgeschort omdat het bestuursorgaan derden om hun zienswijze heeft gevraagd en tenslotte nog eens 42 dagen bij de instelling van een adviescommissie.</p>
<h3>Deadline aantekenen bezwaar</h3>
<p>De deadline voor het aantekenen van bezaar wordt berekend op basis van de dagtekening van de beslissing op verzoek, vermeerderd met 42 dagen.</p>
<h3>Deadline aantekenen beroep</h3>
<p>De deadline voor het aantekenen van beroep wordt berekend op basis van de dagtekening van de beslissing op bezwaar, vermeerderd met 43 dagen (de termijn is 42 dagen en begint op de dag n&aactue; bekendmaking van het besluit).</p>
<h3>Fase van het verzoek</h3>
<p>De status van het verzoek wordt berekend op de aangegeven status.</p>
<h3>Status van het verzoek</h3>
<p>Dit veld geeft de status van het verzoek aan en kan &quot;open&quot; of &quot;afgerond&quot; zijn.
<p>Voor de berekening van het veld wordt in de eerste plaats gekeken naar het veld &quot;Reden be&euml;indiging&quot;. Als hier is ingevuld is, wordt het verzoek als afgerond beschouwd. Zo niet, dan wordt gekeken naar de fase waarin het verzoek is. Is er inhoudelijk beroep aangetekend en is dat afgerond, dan wordt het verzoek als afgerond beschouwd. Als het beroep niet is afgerond, is het verzoek nog &quot;open&quot;. Als er nog geen beroep is aangetekend, maar wel bezwaar en er is nog geen beslissing op bezwaar, dan is het beroep &quot;open&quot;. Dat is ook het geval als er wel al een beslissing op bezwaar is genomen, maar de deadline voor het aantekenen van beroep nog niet is verstreken. Is ook die deadline verstreken, dan wordt het verzoek als &quot;afgerond&quot; beschouwd. In het geval dat ook nog geen bezwaar was aangetekend, maar wel al een beslissing op het verzoek was genomen, wordt gekeken naar de deadline voor het aantekenen van bezwaar. Is die datum al gepasseerd, dan is het verzoek &quot;afgerond&quot;. Als dat niet het geval is, of als nog geen beslissing op het verzoek genomen was, dan is het verzoek &quot;open&quot;.</p>
<h3>Duur fase verzoek</h3>
<p>Als er al een beslissing op het verzoek is genomen, wordt dit veld berekend aan de hand van het verschil in dagen tussen de datum van verzending van het verzoek, vermeerderd met 1 dag en de datum van de dagtekening van de beslissing. Is nog geen beslissing genomen, wordt dit veld berekend aan de hand van het verschil in dagen tussen de datum van verzending van het verzoek, vermeerderd met 1 dag en datum van vandaag.</p>
<h3>Duur fase bezwaar</h3>
<p>Als er al een beslissing op het bezwaarschrift is genomen, wordt dit veld berekend aan de hand van het verschil in dagen tussen de datum van verzending van het verzoek, vermeerderd met 1 dag en de datum van de dagtekening van de beslissing. Is nog geen beslissing genomen, wordt dit veld berekend aan de hand van het verschil in dagen tussen de datum van verzending van het verzoek, vermeerderd met 1 dag en datum van vandaag.</p>
<h3>Duur fase beroep</h3>
<p>Als er al een uitspraak van de rechter is, wordt dit veld berekend aan de hand van het verschil in dagen tussen de datum van verzending van het beroep, vermeerderd met 1 dag en de datum van de dagtekening van de beslissing. Is nog geen beslissing genomen, wordt dit veld berekend aan de hand van het verschil in dagen tussen de datum van verzending van het verzoek, vermeerderd met 1 dag en datum van vandaag.</p>
